spring:
  main:
    allow-circular-references: true


doc:
  documentName: Устав, Должностная инструкция , Положение, Штатное расписание,Приказ
  documentText: Повышение уровня гражданского сознания, Системы обучения кадров, Количественный рост, Значимость этих проблем ,Соображения высшего порядка

