spring:
  main:
    allow-circular-references: true


doc:
  documentName: Устав, Должностная инструкция , Положение, Штатное расписание,Приказ
  documentText: Повышение уровня гражданского сознания, Системы обучения кадров, Количественный рост, Значимость этих проблем ,Соображения высшего порядка
  documentAuthor: Бабошин Петр Петрович, Дацюк Павел Константинович,Кучеров Никита Сергеевич,Кросби Сидни Юрьевич,Джобс Стив Олегович
  documentControl: Подтверждение автора, Проверка тестировщика,Не назначено
  documentControlPerson: Артур Баво Сергеевич,Гвардиола Пеп Сергеевич, Кавальчук Алексей Павлович
  documentIncomingList:  Главный документ, Отпуск, Больничный, Выходной, Увольнение
  documentDistPerson:  Петров Петр Петрович", "Админ Админ Админовчи","Гвардиола Пеп Сергеевич","Rik Nikols Pool","Gleen Satoshi Nikamota"));
  documentOutName: Архив, Отдел кадров, Отдел программирования, Отдел производства ,Маркетинг
  docDeliveryType:  Голубями, Email, RocketChat, Гонцом, Почтой России