spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:derby:C:\Derby\db-derby-10.13.1.1-bin\mydb
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    username: app
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/migration/master.xml
    default-schema: public

doc:
  documentName: Устав, Должностная инструкция , Положение, Штатное расписание,Приказ
  documentText: Повышение уровня гражданского сознания, Системы обучения кадров, Количественный рост, Значимость этих проблем ,Соображения высшего порядка
