spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: qwerty
    driverClassName: org.postgresql.Driver

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/migration/master.xml
    default-schema: public

doc:
  documentName: Устав, Должностная инструкция , Положение, Штатное расписание,Приказ
  documentText: Повышение уровня гражданского сознания, Системы обучения кадров, Количественный рост, Значимость этих проблем ,Соображения высшего порядка
